# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/morgan/opdrachten/IMVIS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/morgan/opdrachten/IMVIS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/morgan/opdrachten/IMVIS/CMakeFiles /home/morgan/opdrachten/IMVIS//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/morgan/opdrachten/IMVIS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IMVIS

# Build rule for target.
IMVIS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IMVIS
.PHONY : IMVIS

# fast build rule for target.
IMVIS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMVIS.dir/build.make CMakeFiles/IMVIS.dir/build
.PHONY : IMVIS/fast

code/Histogram.o: code/Histogram.cpp.o
.PHONY : code/Histogram.o

# target to build an object file
code/Histogram.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMVIS.dir/build.make CMakeFiles/IMVIS.dir/code/Histogram.cpp.o
.PHONY : code/Histogram.cpp.o

code/Histogram.i: code/Histogram.cpp.i
.PHONY : code/Histogram.i

# target to preprocess a source file
code/Histogram.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMVIS.dir/build.make CMakeFiles/IMVIS.dir/code/Histogram.cpp.i
.PHONY : code/Histogram.cpp.i

code/Histogram.s: code/Histogram.cpp.s
.PHONY : code/Histogram.s

# target to generate assembly for a file
code/Histogram.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMVIS.dir/build.make CMakeFiles/IMVIS.dir/code/Histogram.cpp.s
.PHONY : code/Histogram.cpp.s

code/Mirror.o: code/Mirror.cpp.o
.PHONY : code/Mirror.o

# target to build an object file
code/Mirror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMVIS.dir/build.make CMakeFiles/IMVIS.dir/code/Mirror.cpp.o
.PHONY : code/Mirror.cpp.o

code/Mirror.i: code/Mirror.cpp.i
.PHONY : code/Mirror.i

# target to preprocess a source file
code/Mirror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMVIS.dir/build.make CMakeFiles/IMVIS.dir/code/Mirror.cpp.i
.PHONY : code/Mirror.cpp.i

code/Mirror.s: code/Mirror.cpp.s
.PHONY : code/Mirror.s

# target to generate assembly for a file
code/Mirror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMVIS.dir/build.make CMakeFiles/IMVIS.dir/code/Mirror.cpp.s
.PHONY : code/Mirror.cpp.s

code/h-nse-imvis.o: code/h-nse-imvis.cpp.o
.PHONY : code/h-nse-imvis.o

# target to build an object file
code/h-nse-imvis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMVIS.dir/build.make CMakeFiles/IMVIS.dir/code/h-nse-imvis.cpp.o
.PHONY : code/h-nse-imvis.cpp.o

code/h-nse-imvis.i: code/h-nse-imvis.cpp.i
.PHONY : code/h-nse-imvis.i

# target to preprocess a source file
code/h-nse-imvis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMVIS.dir/build.make CMakeFiles/IMVIS.dir/code/h-nse-imvis.cpp.i
.PHONY : code/h-nse-imvis.cpp.i

code/h-nse-imvis.s: code/h-nse-imvis.cpp.s
.PHONY : code/h-nse-imvis.s

# target to generate assembly for a file
code/h-nse-imvis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMVIS.dir/build.make CMakeFiles/IMVIS.dir/code/h-nse-imvis.cpp.s
.PHONY : code/h-nse-imvis.cpp.s

code/invert.o: code/invert.cpp.o
.PHONY : code/invert.o

# target to build an object file
code/invert.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMVIS.dir/build.make CMakeFiles/IMVIS.dir/code/invert.cpp.o
.PHONY : code/invert.cpp.o

code/invert.i: code/invert.cpp.i
.PHONY : code/invert.i

# target to preprocess a source file
code/invert.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMVIS.dir/build.make CMakeFiles/IMVIS.dir/code/invert.cpp.i
.PHONY : code/invert.cpp.i

code/invert.s: code/invert.cpp.s
.PHONY : code/invert.s

# target to generate assembly for a file
code/invert.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IMVIS.dir/build.make CMakeFiles/IMVIS.dir/code/invert.cpp.s
.PHONY : code/invert.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... IMVIS"
	@echo "... code/Histogram.o"
	@echo "... code/Histogram.i"
	@echo "... code/Histogram.s"
	@echo "... code/Mirror.o"
	@echo "... code/Mirror.i"
	@echo "... code/Mirror.s"
	@echo "... code/h-nse-imvis.o"
	@echo "... code/h-nse-imvis.i"
	@echo "... code/h-nse-imvis.s"
	@echo "... code/invert.o"
	@echo "... code/invert.i"
	@echo "... code/invert.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

